CREATE DATABASE qyu5069_db_PagesFramesAndPixels;
USE qyu5069_db_PagesFramesAndPixels;

CREATE OR REPLACE TABLE CREATOR(
    CRE_ID INT PRIMARY KEY,
    CRE_LNAME VARCHAR(30),
    CRE_FNAME VARCHAR(30)
);
DESCRIBE CREATOR;
CREATE OR REPLACE TABLE COUNTRY(
    COUNTRY_ID INT PRIMARY KEY,
    COUNTRY_NAME VARCHAR(30)
);

CREATE OR REPLACE TABLE SERIES(
    SERIES_ID INT PRIMARY KEY,
    SERIES_NAME VARCHAR(100) NOT NULL,
    SERIES_TYPE VARCHAR(30),
    SERIES_GENRE VARCHAR(30),
    COUNTRY_ID INT,
    CRE_ID INT,
    FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRY(COUNTRY_ID),
    FOREIGN KEY (CRE_ID) REFERENCES CREATOR(CRE_ID)
);

CREATE OR REPLACE TABLE SUPPLIER(
    SUPP_ID INT PRIMARY KEY,
    SUPP_NAME VARCHAR(30) NOT NULL,
    SUPP_PHONE CHAR(12),
    COUNTRY_ID INT,
    FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRY(COUNTRY_ID)
);

CREATE OR REPLACE TABLE PRODUCT(
    PROD_ID INT PRIMARY KEY,
    PROD_QOH INT,
    PROD_PRICE DECIMAL(10,2),
    SERIES_ID INT,
    SUPP_ID INT,
    FOREIGN KEY(SERIES_ID) REFERENCES SERIES(SERIES_ID),
    FOREIGN KEY (SUPP_ID) REFERENCES SUPPLIER(SUPP_ID)
);

CREATE OR REPLACE TABLE PLUSH(
    PROD_ID INT PRIMARY KEY,
    PLU_NAME VARCHAR(30) NOT NULL,
    PLU_MAT VARCHAR(30),
    FOREIGN KEY (PROD_ID) REFERENCES PRODUCT(PROD_ID)
);

CREATE OR REPLACE TABLE ACCESSORY(
    PROD_ID INT PRIMARY KEY,
    ACC_NAME VARCHAR(30) NOT NULL,
    ACC_MAT VARCHAR(30),
    ACC_TYPE VARCHAR(30),
    FOREIGN KEY (PROD_ID) REFERENCES PRODUCT(PROD_ID)
);

CREATE OR REPLACE TABLE HOME(
    PROD_ID INT PRIMARY KEY,
    HOME_NAME VARCHAR(30),
    HOME_MAT VARCHAR(30),
    HOME_TYPE VARCHAR(30),
    FOREIGN KEY (PROD_ID) REFERENCES PRODUCT(PROD_ID)
);

CREATE OR REPLACE TABLE CUSTOMER(
    CUS_ID INT PRIMARY KEY,
    CUS_FNAME VARCHAR(30),
    CUS_LNAME VARCHAR(30),
    CUS_EMAIL VARCHAR(30),
    CUS_PHONE CHAR(12),
    CUS_ADR VARCHAR(30),
    CUS_STATE VARCHAR(30),
    CUS_COUNTRY VARCHAR(30),
    MEM_STATUS VARCHAR(30)
    );

CREATE OR REPLACE TABLE INVOICE(
    INV_ID INT PRIMARY KEY,
    INV_DATE DATE,
    INV_TOTAL DECIMAL(10,2),
    CUS_ID INT,
    FOREIGN KEY (CUS_ID) REFERENCES CUSTOMER(CUS_ID)
);

CREATE OR REPLACE TABLE INV_HIST(
    HIST_ID INT PRIMARY KEY,
    INV_ID INT,
    FOREIGN KEY (INV_ID) REFERENCES INVOICE(INV_ID)
);

CREATE OR REPLACE TABLE LINE(
    LINE_ID INT PRIMARY KEY,
    INV_ID INT,
    PROD_ID INT,
    LINE_QTY INT,
    LINE_PRICE DECIMAL(10,2),
    FOREIGN KEY (PROD_ID) REFERENCES PRODUCT(PROD_ID),
    FOREIGN KEY (INV_ID) REFERENCES INVOICE(INV_ID)
);
CREATE OR REPLACE TABLE MEMBERSHIP(
    MEM_ID INT PRIMARY KEY,
    MEM_TYPE VARCHAR(30),
    CUS_ID INT,
    FOREIGN KEY (CUS_ID) REFERENCES CUSTOMER(CUS_ID)
);
